# Generated by Django 6.0.1 on 2026-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default='support@kerala.gov.in', max_length=254),
        ),
    ]
