# Generated by Django 6.0.2 on 2026-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_officialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Checked by a human official'),
        ),
    ]
