# Generated by Django 6.0.1 on 2026-03-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
    ]
