# Generated by Django 6.0.1 on 2026-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
    ]
